// proto/game.proto

// Purpose: Strict gRPC API contract for Dual-Agent routing and game state
// Author: Nahasat Nibir (Lead Cloud Architect)
// Date: 2026-03-06
// Dependencies: protoc, protoc-gen-go, protoc-gen-go-grpc

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: game.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DualAgentEngine_ProcessChatEvent_FullMethodName = "/vaultsim.v1.DualAgentEngine/ProcessChatEvent"
	DualAgentEngine_ValidateSession_FullMethodName  = "/vaultsim.v1.DualAgentEngine/ValidateSession"
)

// DualAgentEngineClient is the client API for DualAgentEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DualAgentEngine handles the conversational AI and isolated judging
type DualAgentEngineClient interface {
	// Streams the user's chat event to the Python AI service and returns the Persona's response
	// along with any asynchronous score updates from the Judge agent.
	ProcessChatEvent(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResponse], error)
	// Validates a scenario session initialization
	ValidateSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
}

type dualAgentEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewDualAgentEngineClient(cc grpc.ClientConnInterface) DualAgentEngineClient {
	return &dualAgentEngineClient{cc}
}

func (c *dualAgentEngineClient) ProcessChatEvent(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DualAgentEngine_ServiceDesc.Streams[0], DualAgentEngine_ProcessChatEvent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DualAgentEngine_ProcessChatEventClient = grpc.ServerStreamingClient[ChatResponse]

func (c *dualAgentEngineClient) ValidateSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, DualAgentEngine_ValidateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DualAgentEngineServer is the server API for DualAgentEngine service.
// All implementations must embed UnimplementedDualAgentEngineServer
// for forward compatibility.
//
// DualAgentEngine handles the conversational AI and isolated judging
type DualAgentEngineServer interface {
	// Streams the user's chat event to the Python AI service and returns the Persona's response
	// along with any asynchronous score updates from the Judge agent.
	ProcessChatEvent(*ChatRequest, grpc.ServerStreamingServer[ChatResponse]) error
	// Validates a scenario session initialization
	ValidateSession(context.Context, *SessionRequest) (*SessionResponse, error)
	mustEmbedUnimplementedDualAgentEngineServer()
}

// UnimplementedDualAgentEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDualAgentEngineServer struct{}

func (UnimplementedDualAgentEngineServer) ProcessChatEvent(*ChatRequest, grpc.ServerStreamingServer[ChatResponse]) error {
	return status.Error(codes.Unimplemented, "method ProcessChatEvent not implemented")
}
func (UnimplementedDualAgentEngineServer) ValidateSession(context.Context, *SessionRequest) (*SessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateSession not implemented")
}
func (UnimplementedDualAgentEngineServer) mustEmbedUnimplementedDualAgentEngineServer() {}
func (UnimplementedDualAgentEngineServer) testEmbeddedByValue()                         {}

// UnsafeDualAgentEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DualAgentEngineServer will
// result in compilation errors.
type UnsafeDualAgentEngineServer interface {
	mustEmbedUnimplementedDualAgentEngineServer()
}

func RegisterDualAgentEngineServer(s grpc.ServiceRegistrar, srv DualAgentEngineServer) {
	// If the following call panics, it indicates UnimplementedDualAgentEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DualAgentEngine_ServiceDesc, srv)
}

func _DualAgentEngine_ProcessChatEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DualAgentEngineServer).ProcessChatEvent(m, &grpc.GenericServerStream[ChatRequest, ChatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DualAgentEngine_ProcessChatEventServer = grpc.ServerStreamingServer[ChatResponse]

func _DualAgentEngine_ValidateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DualAgentEngineServer).ValidateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DualAgentEngine_ValidateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DualAgentEngineServer).ValidateSession(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DualAgentEngine_ServiceDesc is the grpc.ServiceDesc for DualAgentEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DualAgentEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vaultsim.v1.DualAgentEngine",
	HandlerType: (*DualAgentEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateSession",
			Handler:    _DualAgentEngine_ValidateSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessChatEvent",
			Handler:       _DualAgentEngine_ProcessChatEvent_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "game.proto",
}
