# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import game_pb2 as game__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in game_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DualAgentEngineStub(object):
    """DualAgentEngine handles the conversational AI and isolated judging
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessChatEvent = channel.unary_stream(
                '/vaultsim.v1.DualAgentEngine/ProcessChatEvent',
                request_serializer=game__pb2.ChatRequest.SerializeToString,
                response_deserializer=game__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.ValidateSession = channel.unary_unary(
                '/vaultsim.v1.DualAgentEngine/ValidateSession',
                request_serializer=game__pb2.SessionRequest.SerializeToString,
                response_deserializer=game__pb2.SessionResponse.FromString,
                _registered_method=True)


class DualAgentEngineServicer(object):
    """DualAgentEngine handles the conversational AI and isolated judging
    """

    def ProcessChatEvent(self, request, context):
        """Streams the user's chat event to the Python AI service and returns the Persona's response
        along with any asynchronous clue updates from the Judge agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSession(self, request, context):
        """Validates a scenario session initialization
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DualAgentEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessChatEvent': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessChatEvent,
                    request_deserializer=game__pb2.ChatRequest.FromString,
                    response_serializer=game__pb2.ChatResponse.SerializeToString,
            ),
            'ValidateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSession,
                    request_deserializer=game__pb2.SessionRequest.FromString,
                    response_serializer=game__pb2.SessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vaultsim.v1.DualAgentEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vaultsim.v1.DualAgentEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DualAgentEngine(object):
    """DualAgentEngine handles the conversational AI and isolated judging
    """

    @staticmethod
    def ProcessChatEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vaultsim.v1.DualAgentEngine/ProcessChatEvent',
            game__pb2.ChatRequest.SerializeToString,
            game__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vaultsim.v1.DualAgentEngine/ValidateSession',
            game__pb2.SessionRequest.SerializeToString,
            game__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
