# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\x0bvaultsim.v1\"V\n\x0b\x43hatRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"\x80\x01\n\x0c\x43hatResponse\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x15\n\rpersona_reply\x18\x02 \x01(\t\x12\x17\n\x0fsecret_revealed\x18\x03 \x01(\x08\x12\x13\n\x0bscore_delta\x18\x04 \x01(\x05\x12\x19\n\x11judge_explanation\x18\x05 \x01(\t\"J\n\x0eSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x13\n\x0bscenario_id\x18\x03 \x01(\t\"P\n\x0fSessionResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x14\n\x0cpersona_role\x18\x03 \x01(\t2\xaa\x01\n\x0f\x44ualAgentEngine\x12I\n\x10ProcessChatEvent\x12\x18.vaultsim.v1.ChatRequest\x1a\x19.vaultsim.v1.ChatResponse0\x01\x12L\n\x0fValidateSession\x12\x1b.vaultsim.v1.SessionRequest\x1a\x1c.vaultsim.v1.SessionResponseB\"Z vaultsim/gateway/internal/rpc/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z vaultsim/gateway/internal/rpc/pb'
  _globals['_CHATREQUEST']._serialized_start=27
  _globals['_CHATREQUEST']._serialized_end=113
  _globals['_CHATRESPONSE']._serialized_start=116
  _globals['_CHATRESPONSE']._serialized_end=244
  _globals['_SESSIONREQUEST']._serialized_start=246
  _globals['_SESSIONREQUEST']._serialized_end=320
  _globals['_SESSIONRESPONSE']._serialized_start=322
  _globals['_SESSIONRESPONSE']._serialized_end=402
  _globals['_DUALAGENTENGINE']._serialized_start=405
  _globals['_DUALAGENTENGINE']._serialized_end=575
# @@protoc_insertion_point(module_scope)
